import type { QuestionnaireSection } from '@/lib/estimating/questionnaire/questionnaire-types';

export const COMMON_QUESTIONNAIRE_SECTIONS: QuestionnaireSection[] = [
  {
    id: 'commercial-basis',
    title: 'Commercial Basis',
    description: 'Define the commercial basis, waste, markup, and labor approach before the estimate is finalized.',
    accent: 'gold',
    questions: [
      {
        id: 'materialMarkupPercent',
        type: 'number',
        label: 'Material markup',
        description: 'Additional material markup applied before summary-level overhead and profit.',
        defaultValue: 0,
        min: 0,
        max: 35,
        step: 1,
        suffix: '%',
      },
      {
        id: 'wastePercent',
        type: 'single_select',
        label: 'Waste factor',
        description: 'Applied to material-heavy line items to cover cuts, loss, and practical field carry.',
        defaultValue: '0',
        displayStyle: 'cards',
        options: [
          { value: '0', label: '0%', description: 'Exact takeoff only' },
          { value: '5', label: '5%', description: 'Low waste allowance' },
          { value: '10', label: '10%', description: 'Standard field allowance' },
          { value: '15', label: '15%', description: 'High field allowance' },
          { value: '20', label: '20%', description: 'Heavy waste carry' },
        ],
      },
      {
        id: 'laborPricingModel',
        type: 'single_select',
        label: 'Labor pricing model',
        description: 'Controls labor basis messaging and labor factor adjustments.',
        defaultValue: 'project',
        displayStyle: 'cards',
        options: [
          { value: 'hour', label: 'Per Hour', description: 'Time-and-material leaning basis' },
          { value: 'day', label: 'Per Day', description: 'Day-rate driven production basis' },
          { value: 'person', label: 'Per Person', description: 'Headcount-based carry' },
          { value: 'crew', label: 'Per Crew', description: 'Crew output pricing' },
          { value: 'project', label: 'Per Project', description: 'Lump-sum labor carry' },
        ],
      },
    ],
  },
  {
    id: 'job-conditions',
    title: 'Job Conditions',
    description: 'Reflect site access, urgency, overtime pressure, and commercial allowances.',
    accent: 'slate',
    questions: [
      {
        id: 'accessDifficulty',
        type: 'single_select',
        label: 'Site access difficulty',
        defaultValue: 'standard',
        displayStyle: 'cards',
        options: [
          { value: 'standard', label: 'Standard', description: 'Normal staging and access' },
          { value: 'restricted', label: 'Restricted', description: 'Tighter staging or sequencing' },
          { value: 'congested', label: 'Congested', description: 'Heavy coordination or difficult logistics' },
        ],
      },
      {
        id: 'scheduleUrgency',
        type: 'single_select',
        label: 'Schedule urgency',
        defaultValue: 'standard',
        displayStyle: 'cards',
        options: [
          { value: 'standard', label: 'Standard', description: 'Normal delivery window' },
          { value: 'accelerated', label: 'Accelerated', description: 'Compressed scheduling' },
          { value: 'rush', label: 'Rush', description: 'High-pressure production carry' },
        ],
      },
      {
        id: 'overtimeRequired',
        type: 'boolean',
        label: 'Overtime or premium time expected',
        description: 'Add labor pressure for nights, weekends, or compressed phasing.',
        defaultValue: false,
      },
      {
        id: 'contingencyPercent',
        type: 'number',
        label: 'Contingency allowance',
        defaultValue: 3,
        min: 0,
        max: 20,
        step: 1,
        suffix: '%',
      },
      {
        id: 'taxPercent',
        type: 'number',
        label: 'Sales tax',
        defaultValue: 0,
        min: 0,
        max: 15,
        step: 0.25,
        suffix: '%',
      },
    ],
  },
];
